from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# High-density surfaces where a canonical player/team/game identity without an
# entity route is a product regression. This remains source-contract based rather
# than depending on bundled release assets, which are intentionally generated by
# the data pipeline instead of committed as fake production data.
CONTRACTS: dict[str, tuple[str, ...]] = {
    "lib/screens/product_nba_public_pages_screen.dart": (
        "openNbaPlayerPage(context, row.playerId, row.player)",
        "openNbaTeamPage(context, id, id)",
        "openNbaGamePage(",
        "Open Game Command Center",
        "class ProductNbaPlayerPage",
        "class ProductNbaTeamPage",
        "class ProductNbaHubV2Screen",
        "_GameCard",
        "_GameTeamLink",
        "_StandingRow",
    ),
    "lib/screens/product_nba_game_command_center_screen.dart": (
        "class ProductNbaGameCommandCenterScreen",
        "NbaGameIntelligenceEngine",
        "NbaGameWorkflowService",
        "GAME WORKFLOWS",
        "game-route-workspace",
        "game-route-python",
        "game-route-source-audit",
        "game-activate-research",
        "game-toggle-watch",
        "onOpenTeam",
        "onOpenPlayer",
        "PLAYER BOX SCORE",
        "SOURCE & PROVENANCE",
    ),
    "lib/services/nba_game_workflow_service.dart": (
        "RoutePayload route(",
        "activateResearch(",
        "watchItem(",
        "toggleWatch(",
        "sourceObjectType",
    ),
    "lib/services/nba_game_schedule_engine.dart": (
        "class NbaGameScheduleEngine",
        "class NbaGameScheduleResult",
        "class NbaGameScheduleRow",
        "teamId",
        "dateFrom",
        "dateTo",
        "datasetStatus",
    ),
    "lib/screens/product_nba_schedule_screen.dart": (
        "class ProductNbaScheduleScreen",
        "Canonical game calendar",
        "schedule-search",
        "schedule-game-",
        "onOpenGame",
        "onOpenTeam",
        "VALIDATION",
    ),
    "lib/widgets/nba_game_navigation.dart": (
        "openNbaGamePage(",
        "'/nba/games/",
        "ProductNbaGameCommandCenterScreen",
        "openNbaSchedulePage(",
        "'/nba/schedule'",
        "ProductNbaScheduleScreen",
        "open-nba-schedule",
        "onOpenTeam",
        "onOpenPlayer",
    ),
    "lib/screens/product_nba_terminal_screen.dart": (
        "('games', 'game', Icons.sports_basketball_rounded)",
        "kind == 'game'",
        "openNbaGamePage(",
        "gameKey:",
    ),
    "lib/services/sports_object_router.dart": (
        "RoutePayload packageGame(",
        "sourceObjectType: 'NBA Game'",
        "'game_id'",
        "'integrityBlockers'",
    ),
    "lib/screens/product_nba_advanced_stats_page_screen.dart": (
        "openNbaPlayerPage(context, row.playerId, row.player)",
        "openNbaTeamPage(context, id, id)",
    ),
    "lib/screens/product_nba_awards_v2_screen.dart": (
        "_openHistoricalPlayerPage(",
        "ProductHistoricalPlayerDossier(",
        "class _AwardHistoryRow",
    ),
    "lib/screens/product_trade_machine_v2_screen.dart": (
        "openNbaTeamPage(context, team, team)",
        "openNbaPlayerPage(context, view.playerId, view.asset.label)",
        "class _AssetRouteRow",
    ),
    "lib/screens/product_team_blogs_screen.dart": (
        "openNbaPlayerPage(context, row.playerId, row.player)",
        "openNbaTeamPage(context, team, team)",
        "openNbaGamePage(",
        "Open Game Command Center",
        "onOpenTeam",
        "_firstGameValue(",
        "'opponent_team_id'",
    ),
    "lib/screens/product_historical_nba_entity_dossier.dart": (
        "class ProductHistoricalPlayerDossier",
        "class ProductHistoricalTeamDossier",
        "nbaTerminalStatFamilies",
        "NbaStatsSeasonType.playoffs",
    ),
}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--json", default="artifacts/nba_entity_link_audit.json")
    args = parser.parse_args()

    failures: list[dict[str, str]] = []
    passed = 0
    assertions = 0
    for relative, required in CONTRACTS.items():
        path = ROOT / relative
        if not path.exists():
            failures.append({"path": relative, "missing": "<file>"})
            continue
        text = path.read_text(encoding="utf-8")
        for token in required:
            assertions += 1
            if token not in text:
                failures.append({"path": relative, "missing": token})
            else:
                passed += 1

    payload = {
        "contract": "canonical-player-team-game-workflows-schedule-v4-all-era",
        "surfaces": len(CONTRACTS),
        "assertions": assertions,
        "passed": passed,
        "failures": failures,
    }
    output = ROOT / args.json
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(json.dumps(payload, indent=2))
    return 1 if args.check and failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
