#!/usr/bin/env bash
set -euo pipefail

flutter test test/player_identity_validator_test.dart test/player_identity_normalizer_test.dart test/player_identity_import_readiness_service_test.dart test/search_route_payload_player_producer_test.dart test/player_season_stat_validator_test.dart test/team_season_stat_validator_test.dart test/standings_record_validator_test.dart test/playoff_series_validator_test.dart test/award_record_validator_test.dart test/game_record_validator_test.dart test/roster_entry_validator_test.dart test/draft_pick_validator_test.dart test/transaction_record_validator_test.dart test/early_data_wave_readiness_service_test.dart test/compact_metric_card_test.dart

echo "Pre-data test suite passed."
